name: GCP

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # ensure
      ## TODO: use Terraform instead
      - run: ./pleasew run //kubernetes/gcp:cluster -- ensure
      ## TODO: use outputs from Terraform
      - run: ./pleasew run //socks/gcp:bastion -- ensure
      
      # test
      - run: ./pleasew run //socks/gcp/test
      
      # cleanup
      - run: ./pleasew run //socks/gcp:bastion -- cleanup
      ## TODO: use Terraform instead
      - run: ./pleasew run //kubernetes/gcp:cluster -- cleanup
      
