name: E2E

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gcp_test:
    if: github.event_name == 'pull_request'
    name: "GCP"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2

      - id: 'gcp-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/76410834219/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'gha-pr-vjftw-bastion@vjp-github-actions.iam.gserviceaccount.com'

      - name: Create infrastructure
        run: ./pleasew run ///third_party/terraform/org-infra//build/github:terraform_apply -- "//gcp:gcp"

      # # cleanup
      # - run: ./pleasew run //gcp:gcp_destroy -- -force
      #   if: always()
      
